In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

## Data Ingestion

In [2]:
subscribers_df = pd.read_csv(r"C:\Users\sharath\Downloads\project python\raw_data-20251103T030343Z-1-001\raw_data\subscribers.csv", index_col = "Unnamed: 0")
content_df = pd.read_csv(r"C:\Users\sharath\Downloads\project python\raw_data-20251103T030343Z-1-001\raw_data\content.csv", index_col = "Unnamed: 0")
content_consumption_df = pd.read_csv(r"C:\Users\sharath\Downloads\project python\raw_data-20251103T030343Z-1-001\raw_data\content_consumption.csv", index_col = "Unnamed: 0")

###🧩 1️⃣ index_col → used when reading a CSV file
🧩 2️⃣ index= → used when creating a DataFrame manually

In [3]:
subscribers_df.head()

,user_id,age_group,city_tier,subscription_date,subscription_plan,last_active_date,plan_change_date,new_subscription_plan
0,UIDJS0000751588f,18-24,Tier 1,2024-06-10,Premium,NaN,NaN,NaN
1,UIDJS000093eeb86,18-24,Tier 1,2024-11-09,Free,NaN,NaN,NaN
2,UIDJS00010d7fa1e,25-34,Tier 1,2024-08-08,Free,NaN,NaN,NaN
3,UIDJS00013411a85,35-44,Tier 2,2024-05-31,VIP,NaN,NaN,NaN
4,UIDJS0003a3f54cf,35-44,Tier 1,2024-09-20,Premium,NaN,NaN,NaN

In [4]:
content_df.head()

       content_id content_type language   genre  runtime
0  CJSMBEACT2e633        Movie  Bengali  Action       90
1  CJSMBEACT34aec        Movie  Bengali  Action      135
2  CJSMBEACT83b46        Movie  Bengali  Action      120
3  CJSMBECOM12e7a        Movie  Bengali  Comedy      120
4  CJSMBECOM5431a        Movie  Bengali  Comedy      135

In [5]:
content_consumption_df.head()

            user_id device_type  total_watch_time_mins
0  UIDJS877cc0e02c9      Mobile                  14613
1  UIDJS06384e7ff06      Mobile                  13271
2  UIDJSc3997b7beb7      Mobile                   4644
3  UIDJS66726ce2325      Mobile                   5734
4  UIDJS040119b6107      Mobile                   2939

In [6]:
subscribers_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44620 entries, 0 to 44619
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   user_id                44620 non-null  object
 1   age_group              44620 non-null  object
 2   city_tier              44620 non-null  object
 3   subscription_date      44620 non-null  object
 4   subscription_plan      44620 non-null  object
 5   last_active_date       6652 non-null   object
 6   plan_change_date       7090 non-null   object
 7   new_subscription_plan  7090 non-null   object
dtypes: object(8)
memory usage: 3.1+ MB

In [7]:
subscribers_df['subscription_date']=pd.to_datetime(subscribers_df['subscription_date'])

In [8]:
# subscribers_df['subscription_date'] = pd.to_datetime(subscribers_df['subscription_date'])
subscribers_df['last_active_date'] = pd.to_datetime(subscribers_df['last_active_date'])
subscribers_df['plan_change_date'] = pd.to_datetime(subscribers_df['plan_change_date'])

## column Data Validation

In [9]:
subscribers_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44620 entries, 0 to 44619
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   user_id                44620 non-null  object
 1   age_group              44620 non-null  object
 2   city_tier              44620 non-null  object
 3   subscription_date      44620 non-null  datetime64[ns]
 4   subscription_plan      44620 non-null  object
 5   last_active_date       6652 non-null   datetime64[ns]
 6   plan_change_date       7090 non-null   datetime64[ns]
 7   new_subscription_plan  7090 non-null   object
dtypes: datetime64[ns](3), object(5)
memory usage: 3.1+ MB

In [35]:
subscribers_df.describe()

,subscription_date,last_active_date,plan_change_date
count,44620,6652,7090
mean,2024-06-18 07:26:00.376512768,2024-09-07 08:07:04.293445888,2024-08-10 08:20:38.928067840
min,2024-01-01 00:00:00,2024-02-01 00:00:00,2024-02-01 00:00:00
25%,2024-03-26 00:00:00,2024-07-06 00:00:00,2024-05-25 06:00:00
50%,2024-06-19 12:00:00,2024-09-27 00:00:00,2024-08-17 00:00:00
75%,2024-09-11 00:00:00,2024-11-18 00:00:00,2024-11-04 00:00:00
max,2024-11-30 00:00:00,2024-12-29 00:00:00,2024-12-31 00:00:00

In [36]:
content_consumption_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133860 entries, 0 to 133859
Data columns (total 3 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   user_id                133860 non-null  object
 1   device_type            133860 non-null  object
 2   total_watch_time_mins  133860 non-null  int64
dtypes: int64(1), object(2)
memory usage: 4.1+ MB

In [37]:
content_consumption_df.describe()

       total_watch_time_mins
count          133860.000000
mean             7034.509331
std              6342.440494
min                66.000000
25%              2192.000000
50%              5154.000000
75%             10044.000000
max             42635.000000

In [38]:
content_df.describe()

           runtime
count  2360.000000
mean     89.550847
std      52.637611
min       5.000000
25%      30.000000
50%      90.000000
75%     120.000000
max     300.000000